/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdministrativeRole;

import Health.Employee.Employee;
import Health.Enterprise.Enterprise;
import Health.Organization.Organization;
import Health.Role.Role;
import Health.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;


/**
 *
 * @author vivekhanagoji
 */
public class ManageUserAccountJpanel extends javax.swing.JPanel {
    private JPanel container;
    private Enterprise enterprise;
    private static Logger log = Logger.getLogger(ManageUserAccountJpanel.class);
    private static final String CLASS_NAME = ManageUserAccountJpanel.class.getName();
    /**
     * Creates new form ManageUserAccountJpanel
     */
    public ManageUserAccountJpanel(JPanel container, Enterprise enterprise) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        populateData();
        populateOrganizationComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userTbl = new javax.swing.JTable();
        manageuserLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        organizationComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        employeeComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        createUserbtn = new javax.swing.JButton();
        SendOtpButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        phnTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(52, 148, 172));
        setLayout(null);

        userTbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        userTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTbl.setRowHeight(22);
        jScrollPane1.setViewportView(userTbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(270, 110, 452, 264);

        manageuserLbl.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        manageuserLbl.setForeground(new java.awt.Color(255, 255, 255));
        manageuserLbl.setText("Manage User Account");
        add(manageuserLbl);
        manageuserLbl.setBounds(240, 30, 446, 56);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Organization:");
        add(jLabel5);
        jLabel5.setBounds(310, 400, 138, 29);

        organizationComboBox.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        organizationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationComboBoxActionPerformed(evt);
            }
        });
        add(organizationComboBox);
        organizationComboBox.setBounds(510, 410, 210, 31);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee:");
        add(jLabel3);
        jLabel3.setBounds(330, 450, 162, 29);

        employeeComboBox.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        employeeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(employeeComboBox);
        employeeComboBox.setBounds(510, 460, 210, 31);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Role:");
        add(jLabel4);
        jLabel4.setBounds(330, 500, 72, 29);

        roleComboBox.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(roleComboBox);
        roleComboBox.setBounds(510, 500, 210, 31);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name:");
        add(jLabel1);
        jLabel1.setBounds(330, 550, 119, 29);

        nametxt.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        add(nametxt);
        nametxt.setBounds(510, 550, 210, 31);

        passwordTxt.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        add(passwordTxt);
        passwordTxt.setBounds(510, 640, 210, 31);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        add(jLabel2);
        jLabel2.setBounds(330, 640, 130, 29);

        backBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 102));
        backBtn.setText(" Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(290, 700, 112, 28);

        createUserbtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        createUserbtn.setForeground(new java.awt.Color(0, 0, 102));
        createUserbtn.setText("Create User Account");
        createUserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserbtnActionPerformed(evt);
            }
        });
        add(createUserbtn);
        createUserbtn.setBounds(490, 700, 233, 31);

        SendOtpButton.setText("Send OTP");
        SendOtpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendOtpButtonActionPerformed(evt);
            }
        });
        add(SendOtpButton);
        SendOtpButton.setBounds(760, 550, 110, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone Number");
        add(jLabel7);
        jLabel7.setBounds(310, 590, 150, 40);
        add(phnTxt);
        phnTxt.setBounds(510, 590, 210, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/AdministrativeRole/624111.jpg"))); // NOI18N
        jLabel6.setText("Phone Number");
        add(jLabel6);
        jLabel6.setBounds(-160, -80, 1400, 980);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
         container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void organizationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationComboBoxActionPerformed
        // TODO add your handling code here:
           Organization organization = (Organization) organizationComboBox.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
        }

    }//GEN-LAST:event_organizationComboBoxActionPerformed

    private void createUserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserbtnActionPerformed
        // TODO add your handling code here:
           String userName = nametxt.getText().trim();
        String password = passwordTxt.getText();
        Organization organization = (Organization) organizationComboBox.getSelectedItem();
        Employee employee = (Employee) employeeComboBox.getSelectedItem();
        Role role = (Role) roleComboBox.getSelectedItem();
        ArrayList<String>usernamecheck = new ArrayList<>();
        for(UserAccount e: organization.getUserAccountDirectory().getUserAccountList())
        {
            usernamecheck.add(e.getUsername());
            
        }
        if(usernamecheck.contains(userName))
        {
            JOptionPane.showMessageDialog(null,"UserName already exists");
            return;
        }
        if(userName.isEmpty()||password.isEmpty())
        {
         JOptionPane.showMessageDialog(null,"Please enter a Valid input");
            return;   
        }
        log.debug("Enterprise admin creating user with name \t" +userName+ "Role" +role+ "In Organization" +organization+ "\t" +CLASS_NAME);
        organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
        
        populateData();
        nametxt.setText("");
        passwordTxt.setText("");
    }//GEN-LAST:event_createUserbtnActionPerformed

    private void SendOtpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendOtpButtonActionPerformed
        // TODO add your handling code here:

        boolean textSent =SmsSender.sendSms(phnTxt.getText(), "Hey, Your Phone is Successfully Authenticated");
        
        
//        boolean textSent = SmsSender.sendSms(phoneNumberField.getText(), "You have successfully registered to RELIEF Please check your mail for login credentials");
                    
                 
                    
                    if(!textSent) {
                        JOptionPane.showMessageDialog(null, "Enter VALID phone number! ","warning", JOptionPane.WARNING_MESSAGE);
//                        organization.getPersonDirectory().getVolunteerList().remove((Volunteer)person);
                        return;
                    }
        
    }//GEN-LAST:event_SendOtpButtonActionPerformed
public void populateEmployeeComboBox(Organization organization){
        employeeComboBox.removeAllItems();
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            employeeComboBox.addItem(employee);
        }
    }
 public void populateOrganizationComboBox() {
        organizationComboBox.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            organizationComboBox.addItem(organization);
        }
    }
    
private void populateRoleComboBox(Organization organization){
        roleComboBox.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            roleComboBox.addItem(role);
        }
    }
 public void populateData() {

        DefaultTableModel model = (DefaultTableModel) userTbl.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) userTbl.getModel()).addRow(row);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendOtpButton;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createUserbtn;
    private javax.swing.JComboBox employeeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageuserLbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JComboBox organizationComboBox;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTextField phnTxt;
    private javax.swing.JComboBox roleComboBox;
    private javax.swing.JTable userTbl;
    // End of variables declaration//GEN-END:variables
}
