/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.BioTechnologySupplier;


import Health.BioTechnology.BioTechnologyList;
import Health.BioTechnology.BioTechnology;
import Health.EcoSystem;
import Health.Enterprise.Enterprise;
import Health.Location.Location;
import Health.Organization.BioTechnologyOrganization;
import Health.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author vivekhanagoji
 */
public class AddBioTechnologyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddBioTechnologyJPanel
     */
    private BioTechnologyList BioTechnologyList;
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private BioTechnologyOrganization BioTechnologyOrganization;
    private Enterprise enterprise;
    private Location network;
    private static Logger log = Logger.getLogger(AddBioTechnologyJPanel.class);
    private static final String CLASS_NAME = AddBioTechnologyJPanel.class.getName();

    public AddBioTechnologyJPanel(JPanel userProcessContainer, EcoSystem business, UserAccount userAccount, BioTechnologyOrganization BioTechnologyOrganization, Enterprise enterprise, Location network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.enterprise = enterprise;
        this.network = network;
        this.BioTechnologyOrganization = BioTechnologyOrganization;
        populateTable();

    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) BioTechnologyTble.getModel();

        model.setRowCount(0);

        for (BioTechnology d : business.getBioTechnologyList().getBioTechnologyList()) {

            Object[] row = new Object[2];
            row[0] = d.getBioTechnologyId();
            row[1] = d;
            model.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BioTechnologyTble = new javax.swing.JTable();
        BioTechnologytxtField = new javax.swing.JTextField();
        addBioTechnologyBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addChemicalButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        processlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BioTechnologyTble.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 20)); // NOI18N
        BioTechnologyTble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DrugName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BioTechnologyTble.setRowHeight(30);
        jScrollPane1.setViewportView(BioTechnologyTble);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 141, 720, 270));

        BioTechnologytxtField.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 20)); // NOI18N
        BioTechnologytxtField.setForeground(new java.awt.Color(0, 0, 102));
        BioTechnologytxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BioTechnologytxtFieldActionPerformed(evt);
            }
        });
        add(BioTechnologytxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 431, 230, 40));

        addBioTechnologyBtn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 20)); // NOI18N
        addBioTechnologyBtn.setForeground(new java.awt.Color(0, 0, 102));
        addBioTechnologyBtn.setText("ADD Drug");
        addBioTechnologyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBioTechnologyBtnActionPerformed(evt);
            }
        });
        add(addBioTechnologyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 431, 180, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("DRUG");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 431, 123, 40));

        addChemicalButton.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 20)); // NOI18N
        addChemicalButton.setForeground(new java.awt.Color(0, 0, 102));
        addChemicalButton.setText("Add Chemical");
        addChemicalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChemicalButtonActionPerformed(evt);
            }
        });
        add(addChemicalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, -1, -1));

        backButton.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 20)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 0, 102));
        backButton.setText(" Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, -1));

        processlbl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        processlbl.setForeground(new java.awt.Color(0, 0, 102));
        processlbl.setText("Drug Panel");
        add(processlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 300, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Drug.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BioTechnologytxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BioTechnologytxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BioTechnologytxtFieldActionPerformed

    private void addBioTechnologyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBioTechnologyBtnActionPerformed
        // TODO add your handling code here:

        String BioTechnologyName = BioTechnologytxtField.getText().trim();
        if(BioTechnologyName.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"BioTechnology name cannot be empty");
            return;
        }
        ArrayList<String> BioTechnologycheck= new ArrayList<>();
        for(BioTechnology d:business.getBioTechnologyList().getBioTechnologyList())
        {
            BioTechnologycheck.add(d.getBioTechnologyName().toLowerCase());
        }
        if(BioTechnologycheck.contains(BioTechnologyName.toLowerCase()))
        {
            JOptionPane.showMessageDialog(null,"BioTechnology name already exists");
            return;
        }

        business.getBioTechnologyList().addBioTechnologyList().setBioTechnologyName(BioTechnologyName);
        
        populateTable();
        log.debug(userAccount+" "+"added new BioTechnology"+" "+BioTechnologyName);
        BioTechnologytxtField.setText("");

    }//GEN-LAST:event_addBioTechnologyBtnActionPerformed

    private void addChemicalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChemicalButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = BioTechnologyTble.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null, "please select a row ");
            return;
        }
        BioTechnology c = (BioTechnology) BioTechnologyTble.getValueAt(selectedRow, 1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("AddChemicalsJPanel", new AddChemicalsJPanel(userProcessContainer, business, userAccount, BioTechnologyOrganization, enterprise, network, c));
        log.debug(userAccount+" "+"entering add chemicals page");
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addChemicalButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BioTechnologyTble;
    private javax.swing.JTextField BioTechnologytxtField;
    private javax.swing.JButton addBioTechnologyBtn;
    private javax.swing.JButton addChemicalButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel processlbl;
    // End of variables declaration//GEN-END:variables
}
