/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.BioTechnologySupplier;


import Health.Chemical.Chemical;
import Health.EcoSystem;
import Health.Enterprise.Enterprise;
import Health.Location.Location;
import Health.Organization.BioTechnologyOrganization;
import static Health.Organization.Organization.Type.BioTechnology;
import Health.UserAccount.UserAccount;
import javax.swing.JPanel;
import Health.BioTechnology.BioTechnology;
import Health.Gene.Gene;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author vivekhanagoji
 */
public class ExistingBioTechnologyResultsJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ExistingBioTechnologyResultsJpanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private BioTechnologyOrganization BioTechnologyOrganization ;
    private Enterprise enterprise;
    private Location network;
    private BioTechnology BioTechnology;
    private static Logger log = Logger.getLogger(ExistingBioTechnologyResultsJpanel.class);
    private static final String CLASS_NAME = ExistingBioTechnologyResultsJpanel.class.getName();
    public ExistingBioTechnologyResultsJpanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise, BioTechnologyOrganization BioTechnologyOrganization,Location network,BioTechnology BioTechnology) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.BioTechnologyOrganization = BioTechnologyOrganization;
        this.enterprise = enterprise;
        this.network = network;
        this.BioTechnology=BioTechnology;
        populateTable();
        BioTechnologynametxt.setText(BioTechnology.getBioTechnologyName());
        
    }
    
    public void populateTable(){
         DefaultTableModel model = (DefaultTableModel)chemicalGeneTbl.getModel();
        
        model.setRowCount(0);
        Object[] row = new Object[2];
        int i = 0;
            for(Chemical c : BioTechnology.getChemicalList().getChemList()){
                 
                 row[0] = c.getChemicalName();
                 
                    
                    Gene g=  BioTechnology.getGeneHistory().getGeneHistory().get(i);
                      
                      row[1] = g.getGeneName();
                      model.addRow(row);
                     i++;
                 }
                 
            
         
        
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chemicalGeneTbl = new javax.swing.JTable();
        BioTechnologynametxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(0, 0, 102));
        setLayout(null);

        chemicalGeneTbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        chemicalGeneTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ChemicalName", "GeneName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        chemicalGeneTbl.setRowHeight(30);
        chemicalGeneTbl.getTableHeader().setResizingAllowed(false);
        chemicalGeneTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(chemicalGeneTbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(166, 249, 630, 150);

        BioTechnologynametxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        BioTechnologynametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BioTechnologynametxtActionPerformed(evt);
            }
        });
        add(BioTechnologynametxt);
        BioTechnologynametxt.setBounds(424, 183, 250, 36);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Drug Name");
        add(jLabel1);
        jLabel1.setBounds(260, 190, 139, 30);

        backBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 102));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(230, 520, 97, 33);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Existing Drug");
        add(jLabel3);
        jLabel3.setBounds(290, 80, 350, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/BioTechnologySupplier/pills01.gif"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(220, 60, 640, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void BioTechnologynametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BioTechnologynametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BioTechnologynametxtActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabResultsJpanel lrjp = (LabResultsJpanel) component;
        lrjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BioTechnologynametxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable chemicalGeneTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
