/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.ChemicalRole;
import java.util.*;
import Health.WorkQueue.ChemicalWorkRequest;
import Health.WorkQueue.BioTechnologyWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author vivekhanagoji
 */
public class ChemicalProcessRequestJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ChemicalProcessRequestJpanel
     */
    JPanel userProcessContainer;
    ChemicalWorkRequest request;
    private static Logger log = Logger.getLogger(ChemicalProcessRequestJpanel.class);
    private static final String CLASS_NAME = ChemicalProcessRequestJpanel.class.getName();
    public ChemicalProcessRequestJpanel(JPanel userprocessContainer, ChemicalWorkRequest request) {
        initComponents();
        this.userProcessContainer = userprocessContainer;
        this.request = request;
        dateFld.setMinSelectableDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        processlbl = new javax.swing.JLabel();
        datedeliveryBtn = new javax.swing.JLabel();
        dateTxt1 = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        dateFld = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        processlbl.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        processlbl.setForeground(new java.awt.Color(255, 255, 255));
        processlbl.setText("PROCESSING DRUG SUPPLIER REQUEST ");
        add(processlbl);
        processlbl.setBounds(153, 108, 942, 53);

        datedeliveryBtn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        datedeliveryBtn.setText("SELECT DATE OF DELIVERY : ");
        add(datedeliveryBtn);
        datedeliveryBtn.setBounds(80, 269, 375, 41);

        dateTxt1.setEditable(false);
        dateTxt1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        add(dateTxt1);
        dateTxt1.setBounds(502, 272, 261, 41);

        backBtn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 102));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(300, 400, 94, 33);

        updateBtn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(0, 0, 102));
        updateBtn.setText("UPDATE STATUS ");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn);
        updateBtn.setBounds(500, 400, 261, 33);
        add(dateFld);
        dateFld.setBounds(810, 280, 99, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ChemicalRole/Drug101.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(2, -3, 1280, 730);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ChemicalWorkArea dwjp = (ChemicalWorkArea) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        request.setStatus("Completed");
        try{
        int year = dateFld.getCalendar().get(Calendar.YEAR);
        int month = dateFld.getCalendar().get(Calendar.MONTH);
        int day = dateFld.getCalendar().get(Calendar.DAY_OF_MONTH);
        String result = year + "-" + month + "-" + day;
        ((ChemicalWorkRequest) request).setDeliveryTime(result);
        dateTxt1.setText(result);
        JOptionPane.showMessageDialog(null, "Request updated successfully!");
        log.debug("request updated successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null , "please enter the valid date");
            return;
        }
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private com.toedter.calendar.JDateChooser dateFld;
    private javax.swing.JTextField dateTxt1;
    private javax.swing.JLabel datedeliveryBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel processlbl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
